### ISSUE TITLE
aws_security_group_rule is being replaced.

### ISSUE THREAD

**Issue by mdgreenwald** [terraform-aws-modules/terraform-aws-ecs#100]
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/d764aae10c537a381f6098587e877edc0c26798b/modules/service/main.tf#L1312

The service module is using `aws_security_group_rule` which has been replaced/superseded by the aforementioned resources.

"The [aws_vpc_security_group_egress_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_egress_rule) and [aws_vpc_security_group_ingress_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_ingress_rule) resources have been added to address these limitations and **should be used for all new security group rules.**" [[1]](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule)

**Comment by bryantbiggs** [comment]
Is there any particular issue you are seeing with the current implementation?

**Comment by mdgreenwald** [comment]
> Is there any particular issue you are seeing with the current implementation?

Yes, I am seeing the task security group get re-created every time during apply despite no changes being made.

**Comment by bryantbiggs** [comment]
do you have a sample reproduction we can try out?
