### ISSUE TITLE
Module defaults are overwriting USER set by docker image with root

### ISSUE THREAD

**Issue by nick-bob** [terraform-aws-modules/terraform-aws-ecs#102]
## Is your request related to a problem? Please describe.

With the changes introduced with this [PR](https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/101), by default the module is now overwriting the user set by the docker image with the root user. I don't think this should be the default functionality of the module.

## Describe the solution you'd like.

Revert this [line](https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/101/files#diff-28bc80a19e12810ad239a26d08f533cc89218888b325a01eaf473610578e0bcdL567) 

## Describe alternatives you've considered.

Or we could just keep it the way it is. It's no biggie.

## Additional context

This randomly broke my github actions runner, till I explicitly set the user.

**Comment by Zonny** [comment]
Same issue. It broke my containers that are running on non-root
