### ISSUE TITLE
desired_count does not work when using FARGATE capacity provider

### ISSUE THREAD

**Issue by RazvanGherlea** [terraform-aws-modules/terraform-aws-ecs#107]
<img width="824" alt="Screenshot 2023-08-16 at 11 38 21" src="https://github.com/terraform-aws-modules/terraform-aws-ecs/assets/136329544/15fa21ff-fe02-4e85-ac6d-6de12cc854a9">
<img width="835" alt="Screenshot 2023-08-16 at 11 39 23" src="https://github.com/terraform-aws-modules/terraform-aws-ecs/assets/136329544/ca6aa846-e1fd-4428-baa5-3f0a997a318a">

**Comment by bryantbiggs** [comment]
Please complete the issue template provided

**Comment by RazvanGherlea** [comment]
Nice that you are answering on this but if I would complete the issue there would not be any answer in weeks. 
I will figure it out. As you can clearly see the operator in the desired_count it looks like intentionally ignored (Null) when using  FARGATE capacity provider

**Comment by bryantbiggs** [comment]
have you read the provided documentation https://github.com/terraform-aws-modules/terraform-aws-ecs/tree/master/docs#service-1
