### ISSUE TITLE
container-definition module empty variable

### ISSUE THREAD

**Issue by lpossamai** [terraform-aws-modules/terraform-aws-ecs#109]
## Description

I was deploying the `container-definition` module and found out that I had to specify an empty `environment` variable, otherwise I would get the error below:
```
╷
│ Error: Variables not allowed
│ 
│   on <value for var.environment> line 1:
│   (source code not available)
│ 
│ Variables may not be used here.
```

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 5.2.1

- Terraform version:
```
Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.13.1
```

## Reproduction Code [Required]

```HCL
environment = []
```

Not sure if that is expected or not?

**Comment by bryantbiggs** [comment]
please fill in the issue template with the requested information - we are unable to triage/troubleshoot without a reproduction

**Comment by bryantbiggs** [comment]
closing for now - please feel free to submit a new issue with the requested information (reproduction) so we can investigate
