### ISSUE TITLE
EC2 instances created but not added to ECS cluster

### ISSUE THREAD

**Issue by danieldn** [terraform-aws-modules/terraform-aws-ecs#11]
**Summary**

Ran `terraform apply` on complete-ecs/main.tf to create ECS cluster. Confirmed on AWS console the ECS cluster gets created. However, created EC2 instances are not added to cluster.
![image](https://user-images.githubusercontent.com/11370398/65991349-0d158780-e442-11e9-87bc-c6a50507dbe5.png)

**Steps to reproduce:**
- Set following values in complete-ecs/main.tf
```
provider "aws" {
  region = "us-west-2"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 2.0"

  name = local.name

  cidr = "10.1.0.0/16"

  azs             = ["us-west-2a", "us-west-2b"]
  private_subnets = ["10.1.1.0/24", "10.1.2.0/24"]
  public_subnets  = ["10.1.11.0/24", "10.1.12.0/24"]

  enable_nat_gateway = false # this is faster, but should be "true" for real

  tags = {
    Environment = local.environment
    Name        = local.name
  }
}
```
```
  # Auto scaling group
  asg_name                  = local.ec2_resources_name
  vpc_zone_identifier       = module.vpc.private_subnets
  health_check_type         = "EC2"
  min_size                  = 1
  max_size                  = 3
  desired_capacity          = 1
  wait_for_capacity_timeout = 0
```
- Ran terraform init, plan, and apply

**Comment by antonbabenko** [comment]
You need to tell EC2 instances in user-data that they belong to ECS cluster. Use user_data script like this:

```shell
#!/bin/bash
{
  echo "ECS_CLUSTER=${cluster_name}"
} >> /etc/ecs/ecs.config
```

See [Launching an Amazon ECS Container Instance, Step 6g](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html) for more.

**Comment by guohuang** [comment]
I had the same problem. Running the script didn't solve the problem. how do i know if the sh script is ran?

**Comment by cmosguy** [comment]
@guohuang  I had the same issue did you figure out the solution?

**Comment by guohuang** [comment]
@cmosguy no, i gave up. i use the generic terraform resources to solve the problem.

**Comment by Lonli-Lokli** [comment]
@antonbabenko I believe it's because of changes required by Amazon Linux 2, see similar issue  in another repo
https://github.com/arminc/terraform-ecs/issues/24

**Comment by Lonli-Lokli** [comment]
Nevermind, seems like this changes were enough
https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/9
