### ISSUE TITLE
Unable to use cloudwatch group in several environments.

### ISSUE THREAD

**Issue by bohdantverdyi** [terraform-aws-modules/terraform-aws-ecs#113]
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/2604124d05974c2ee47ff7194d62d55ac425a3cb/modules/container-definition/main.tf#L67

Since the service name could be the same across environments, it can cause conflicts when a CloudWatch group already exists while applying to another environment.

If I add the option to logDriver: awslogs-create-group = true, then I can't specify the retention size.

The only way to achieve this is to create a CloudWatch group outside of this module.
It would be great if the module could support a variable override for the CloudWatch group name.

**Comment by bryantbiggs** [comment]
> Since the service name could be the same across environments, it can cause conflicts when a CloudWatch group already exists while applying to another environment.

What does this mean?

**Comment by bohdantverdyi** [comment]
I have two clusters: 'stage' and 'prod.' Both of them have an 'api' service, and the service name is the same in both the stage and prod clusters.

Cloudwatch group created by module will have attempt to create cloudwatch group with the same.

**Comment by bohdantverdyi** [comment]
Remove stale

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.3.0 :tada:
