### ISSUE TITLE
The task role arn is not getting updated

### ISSUE THREAD

**Issue by renatocosta** [terraform-aws-modules/terraform-aws-ecs#119]
I am getting the following error while running terraform apply

`Plan: 1 to add, 1 to change, 1 to destroy.
module.ecs.module.ecs.module.service["worker"].aws_ecs_task_definition.this[0]: Creating...
╷
│ Error: creating ECS Task Definition (worker): ClientException: Container.image should not be null or empty.
│ 
│   with module.ecs.module.ecs.module.service["worker"].aws_ecs_task_definition.this[0],
│   on .terraform/modules/ecs.ecs/modules/service/main.tf line 609, in resource "aws_ecs_task_definition" "this":
│  609: resource "aws_ecs_task_definition" "this" {
│ 
╵
`

Code:

`module "ecs" {
  source  = "terraform-aws-modules/ecs/aws"
  version = "5.2.2"

cluster_name = "terraform"

  cluster_configuration = {
    execute_command_configuration = {
      logging = "OVERRIDE"
      log_configuration = {
        cloud_watch_log_group_name = "/aws/ecs/aws-ecs"
      }
    }
  }

  fargate_capacity_providers = {
    FARGATE = {
      default_capacity_provider_strategy = {
        weight = 50
      }
    }
    FARGATE_SPOT = {
      default_capacity_provider_strategy = {
        weight = 50
      }
    }
  }

  services = {

    worker = {

      enable_execute_command = true

      cpu        = var.worker_cpu
      memory     = var.worker_memory

      container_definitions = {

        tasks_iam_role_arn = "arn:aws:iam::411531107052:role/ecsTaskExecutionRole"  

        worker = {
          cpu        = var.worker_container_cpu
          memory     = var.worker_container_memory
          essential  = true
          image      = "311231107042.dkr.ecr.us-east-1.amazonaws.com/worker:322"
          port_mappings = [
            {
              containerPort = 80
              protocol      = "tcp"
            }
          ]

          entrypoint = ["/usr/src/app/common/CICD/init_worker.sh", "laravel-workers"]

          readonly_root_filesystem = false

          log_configuration = {
            logDriver = "awslogs"
            options = {
                awslogs-group = "/ecs/workers"
                awslogs-region = var.region
                awslogs-stream-prefix = "ecs"
            }
          }

        }

      }

      load_balancer = {
        service = {
          target_group_arn = var.target_group_arn
          container_name   = "worker"
          container_port   = 80
        }
      }

      subnet_ids = var.subnet_ids
      assign_public_ip = true
      
      security_group_ids = var.security_group_ids

    }
  }

}

module "ecs_service" {
  source = "terraform-aws-modules/ecs/aws//modules/service"

  create = false

  create_iam_role = false

  create_task_definition = false

  create_task_exec_iam_role = false
  
  create_task_exec_policy = false

  create_tasks_iam_role = false

  create_security_group = false
}`

Could anyone help me please?

**Comment by jalawala** [comment]
I also see an issue with task role arn is not getting used.

```
module "ecs_service_definition_2" {
  source  = "terraform-aws-modules/ecs/aws//modules/service"
  version = "~> 5.2.2"
  create_iam_role        = false
  tasks_iam_role_arn     =  aws_iam_role.task.arn
---
}
```

I expect the already existing task ARN to be used.  But a new task Role is created with empty IAM permissions.

**Comment by renatocosta** [comment]
I see.

Thank you for letting me know.
