### ISSUE TITLE
ECS Service module overwrites Container Definition default values

### ISSUE THREAD

**Issue by matheus-rdo** [terraform-aws-modules/terraform-aws-ecs#120]
## Description

The ECS Service module is overwriting the AWS default configuration on some container definition attributes.

I found this issue while troubleshooting an application issue related to the `startTimeout` parameter. [AWS Docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html) says it is not required by default, but the ECS Service module is forcing the value 30 if no value is given, and this difference can be confusing for those who use the module.

I also noticed that this also happens for other parameters, such as stopTimeout which is optional from AWS Docs but it has a default value given by the ECS Service module.

## Versions

- Module version [Required]: 5.2.2

- Terraform version: v1.5.7
- Provider version(s): provider registry.terraform.io/hashicorp/aws v5.17.0

## Reproduction Code [Required]

Any example code.

Steps to reproduce the behavior: Apply the TF code and check the container definition

## Expected behavior

I understand that the module is an abstraction to facilitate the use of AWS ECS, but I believe it would be more interesting to follow the AWS definitions, to simplify understanding for those who use it and also make maintenance easier.

**Comment by bryantbiggs** [comment]
its quite common for module to set default values, for various reasons - defaulting to improved security posture, defaulting to ensure smooth operation when new to the service, etc. This is documented in the variables used
