### ISSUE TITLE
Module for Cluster + Service?

### ISSUE THREAD

**Issue by jritsema** [terraform-aws-modules/terraform-aws-ecs#121]
## Is your request related to a problem? Please describe.

The following docs seem to indicate that this repo offers a single module that provisions both a cluster and a service, however, I am not seeing that in the existing modules.  Am I missing something?

https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/README.md?plain=1#L11

https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/modules/cluster/README.md?plain=1#L10

**Comment by bryantbiggs** [comment]
Correct - the root module supports both the cluster creation and n-number of services that will be provisioned on that same cluster https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/2604124d05974c2ee47ff7194d62d55ac425a3cb/examples/complete/main.tf#L28-L48

Or you can define the cluster separate from the service definitions:
- Cluster only example https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/2604124d05974c2ee47ff7194d62d55ac425a3cb/examples/ec2-autoscaling/main.tf#L28
- Service only example https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/2604124d05974c2ee47ff7194d62d55ac425a3cb/examples/ec2-autoscaling/main.tf#L78

**Comment by jritsema** [comment]
Awesome, thanks @bryantbiggs!
