### ISSUE TITLE
container_definitions when using dynamic variables is failing when nothing is deployed yet

### ISSUE THREAD

**Issue by ignatenkobrain** [terraform-aws-modules/terraform-aws-ecs#128]
## Description

When using dynamic variables (e.g. outputs from other modules like `terraform-aws-rds`) in `container_definitions`, the Terraform fails when aforementioned resource does not exist yet.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `5.2.2`

- Terraform version:

```
Terraform v1.6.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.23.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/ns1-terraform/ns1 v2.0.10
```

## Reproduction Code [Required]

Full setup tree (you'll need AWS and NS1 credentials, however you don't have to have valid one to get a relevant error, just `export NS1_APIKEY=xxx`): https://github.com/ignatenkobrain/terraform-netbox-aws/tree/ac1a97ac1b11694f16fffa1cdcc3e3e5d6e2a772

```
export AWS_...
export NS1_APIKEY=secret
terraform init
terraform apply
```

## Expected behavior

No error message and all resources are being properly created.

## Actual behavior

```
Plan: 54 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/app/modules/service/main.tf line 526, in module "container_definition":
│  526:   for_each = { for k, v in var.container_definitions : k => v if local.create_task_definition }
│     ├────────────────
│     │ local.create_task_definition is true
│     │ var.container_definitions will be known only after apply
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
╵
```

## Additional context

If I change https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/e987d950ce4a87cdc7d461665419d8a55d38a01b/main.tf#L102 line to not use `try(each.value.container_definitions, {})` to simply `each.value.container_definitions`, it starts to work without any issues.

**Comment by iycbell** [comment]
Yeah the strangest thing about this issue is that it's sporadic- sometimes an apply will just work. Definitely has been an issue for a while now. Targeting worked for me in the past.

**Comment by Gauthier-kwatatshey** [comment]
Any news on this? I have got the samething.
 on .terraform/modules/ecs.ecs/modules/service/main.tf line 525, in module "container_definition":
│  525:   for_each = { for k, v in var.container_definitions : k => v if local.create_task_definition && try(v.create, true) }
│     ├────────────────
│     │ local.create_task_definition is true
│     │ var.container_definitions will be known only after apply
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the
│ full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results
│ only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a
│ second time to fully converge.

**Comment by iycbell** [comment]
It's definitely annoying. I've been using `-target` as suggested to avoid this collision, which seems really sporadic.

**Comment by donatoaz** [comment]
> It's definitely annoying. I've been using `-target` as suggested to avoid this collision, which seems really sporadic.

Hi iycbell, I have a similar issue. How do I use this `-target` option? I mean, do I need to pass something as a target?

Btw, I am using `cdktf plan`.

**Comment by iycbell** [comment]
> > It's definitely annoying. I've been using `-target` as suggested to avoid this collision, which seems really sporadic.
> 
> Hi iycbell, I have a similar issue. How do I use this `-target` option? I mean, do I need to pass something as a target?
> 
> Btw, I am using `cdktf plan`.

Hi donatoaz. This was a weird issue, but ultimately `target` was a red herring. The plans eventually failed again. A more permanent fix for us was following what OP did in the `additional context` section:
Updating [this line](https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/e987d950ce4a87cdc7d461665419d8a55d38a01b/main.tf#L102) in the module to `each.value.container_definitions`. The logic is that if there is a failure to set the container definitions, it should be caught during our plan/apply. Good luck.
