### ISSUE TITLE
docs: Incorrect default in description of `desired_count`

### ISSUE THREAD

**Issue by baolsen** [terraform-aws-modules/terraform-aws-ecs#129]
In the `service` module, the variable description below is incorrect considering the default value.

Note, "Defaults to 0" could probably be removed entirely, as the default value is displayed in Terraform docs.

```
variable "desired_count" {
  description = "Number of instances of the task definition to place and keep running. Defaults to `0`"
  type        = number
  default     = 1
}
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.6.0 :tada:
