### ISSUE TITLE
readonly_root_filesystem option in container-definition does not work

### ISSUE THREAD

**Issue by sista05** [terraform-aws-modules/terraform-aws-ecs#132]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by sista05** [comment]
@bryantbiggs
I was in the middle of listing an issue, why was it CLOSED?

**Comment by bryantbiggs** [comment]
There's no information

**Comment by sista05** [comment]
@bryantbiggs
I'll add the information and re-open it.
