### ISSUE TITLE
Add runtimePlatform to be able to use cpuArchitecture  = "ARM64" 

### ISSUE THREAD

**Issue by omi-jbrivero** [terraform-aws-modules/terraform-aws-ecs#155]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  Yes but it is around for quite sometime

## Is your request related to a problem? Please describe.
  It's always defaults to x86

## Describe the solution you'd like.
It's always defaults to x86 and we would like to have options for ARM64

## Describe alternatives you've considered.
 None yet

## Additional context
 Output when u config via console
<img width="438" alt="image" src="https://github.com/terraform-aws-modules/terraform-aws-ecs/assets/108859832/6e8b4b93-9745-4f65-bed5-85446509f3ca">

**Comment by bryantbiggs** [comment]
have you tried specifying that value? do you have a reproduction?

**Comment by dotnich-io** [comment]
This bit me today, too. I wondered why my tasks weren't launching and I'm pretty sure this is the reason.

**Comment by dotnich-io** [comment]
This is still an issue.

**Comment by bryantbiggs** [comment]
I have yet to see a reproduction

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.11.1 :tada:
