### ISSUE TITLE
feat: add managed_draining to aws_ecs_capacity_provider

### ISSUE THREAD

**Issue by remiflament** [terraform-aws-modules/terraform-aws-ecs#156]
[AWS provider v5.34.0 added this functionality](https://github.com/hashicorp/terraform-provider-aws/pull/35421)

The minimum version of the module needs to be update as `>= 5.34.0`

Description of this feature : 
- https://aws.amazon.com/fr/about-aws/whats-new/2024/01/amazon-ecs-managed-instance-draining/
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/managed-instance-draining.html

Now if you create a new ecs_capacity_providre **it automatically comes with managed_draining as true**.
I tested it by destroy/re-apply one of my sandbox stack using this module in version `5.7.4`

It could be beneficial to manage whether we want or not this feature.
We have a clear documentation of the combination of `managed_termination` and `managed_draining` on the [official doc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/managed-instance-draining.html#:~:text=The%20following%20table%20summarizes%20the%20behavior%20for%20different%20combinations%20of%20managed%20termination%20and%20managed%20draining.)

I didn't start the PR because I was not sure about the things to do with the upgrade of the minimum version.

Thank you

**Comment by antonbabenko** [comment]
Please make a PR with this change.

**Comment by bryantbiggs** [comment]
resolved in #123

**Comment by ivan-sukhomlyn** [comment]
just to clarify with the correct link:
resolved in https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/158
