### ISSUE TITLE
Should support to AWS China environment

### ISSUE THREAD

**Issue by Wyifei** [terraform-aws-modules/terraform-aws-ecs#161]
## Description

If bootstrap the ECS in AWS China, the script will failed to create the IAM role because the ARN format is different in China.

Current script:
`variable "task_exec_ssm_param_arns" {
  description = "List of SSM parameter ARNs the task execution role will be permitted to get/read"
  type        = list(string)
  default     = ["arn:aws:ssm:*:*:parameter/*"]
}

variable "task_exec_secret_arns" {
  description = "List of SecretsManager secret ARNs the task execution role will be permitted to get/read"
  type        = list(string)
  default     = ["arn:aws:secretsmanager:*:*:secret:*"]
}`

The arn format in china is arn:aws-cn:xxxxxx

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 5.8.0

- Terraform version: 1.4.6

- Provider version(s):

## Expected behavior

The module could support to create the related resources in China successfully.

**Comment by bryantbiggs** [comment]
it is supported, its just that the default value is the standard commercial `aws` partition - its recommended you specify the ARNs you wish to allow
