### ISSUE TITLE
Health Check doesn't support start_period.

### ISSUE THREAD

**Issue by mdgreenwald** [terraform-aws-modules/terraform-aws-ecs#166]
There is an optional parameter for health checks; [startPeriod](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck).

As of today, that parameter doesn't appear to be supported by the Module:
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/8b97783def49997d18a6fcb00dc21ce1edc0f538/modules/container-definition/main.tf#L22-L26

This is really useful for containers which have a long init period; greater than 60 seconds on average.

Reference: [https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck)

**Comment by ivan-sukhomlyn** [comment]
@mdgreenwald, you can add this parameter to the custom `health_check` map variable, and it will be defined in the container definition creation.
The mentioned merge operation is just for safety that default values are added.
Also, you have to add the `command` parameter as well to the `health_check` map
for example,
```
      health_check = {
        command     = ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
        interval    = 30
        retries     = 3
        timeout     = 3
        startPeriod = 60
      }
```

```

**Comment by mdgreenwald** [comment]
@ivan-sukhomlyn Thanks, so the correct parameter is `startPeriod` and not `start_period` as I would expect from other Terraform parameters.

**Comment by ivan-sukhomlyn** [comment]
Yes, the correct one is `startPeriod` as in the mentioned documentation because the ECS container definition at the module is a JSON object that is used at the task definition.

For example, other parameters are defined in camel case style as well
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/8b97783def49997d18a6fcb00dc21ce1edc0f538/modules/container-definition/main.tf#L40-L43

**Comment by mdgreenwald** [comment]
Thanks, sorry for the confusion.
