### ISSUE TITLE
Add TLS Support for ECS Service Connect with ACM PCA.

### ISSUE THREAD

**Issue by jihed** [terraform-aws-modules/terraform-aws-ecs#167]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: [5.37.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5370-february-15-2024)
## Is your request related to a problem? Please describe.

Currently, the ECS Service Connect doesn't support TLS Encryption

## Describe the solution you'd like.
https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-ecs-service-connect-automatic-traffic-encryption-tls-certificates/

**Comment by jihed** [comment]
can you assign to me ? I can work on this.

**Comment by antonbabenko** [comment]
@jihed You can always open a PR, which we will review.
