### ISSUE TITLE
ECS Service on EC2

### ISSUE THREAD

**Issue by monelgordillo** [terraform-aws-modules/terraform-aws-ecs#172]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: [please list the AWS provider version which introduced this functionality](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service)

## Is your request related to a problem? Please describe.
I'm trying to create an ECS service on a EC2 ECS cluster.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-ecs/tree/master/examples/ec2-autoscaling
