### ISSUE TITLE
Enable managed draining for autoscaling_capacity_providers in ecs cluster

### ISSUE THREAD

**Issue by purplepangolin** [terraform-aws-modules/terraform-aws-ecs#174]
## Is your request related to a new offering from AWS?

Amazon recently announced [managed instance draining](https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-ecs-managed-instance-draining/) 

>a new capability that facilitates graceful shutdown of workloads deployed on Amazon Elastic Compute Cloud (Amazon EC2) instances by safely stopping and rescheduling workloads to other, non-terminating instances.

Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? 
 - Yes ✅:
Support for this was added to the terraform aws provider in [release v5.34.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.34.0) and its use is documented [here](https://registry.terraform.io/providers/hashicorp/aws/5.34.0/docs/resources/ecs_capacity_provider#managed_draining).

## Is your request related to a problem? Please describe.
This feature is available by setting the [managed_draining](https://registry.terraform.io/providers/hashicorp/aws/5.34.0/docs/resources/ecs_capacity_provider#managed_draining) property on [aws_ecs_capacity_provider](https://registry.terraform.io/providers/hashicorp/aws/5.34.0/docs/resources/ecs_capacity_provider) but is not exposed in [auto_scaling_group_provider](https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/45f532c06488d84f140af36241d164facb5e05f5/modules/cluster/main.tf#L152)

## Describe the solution you'd like.
Amend the implementation of how [variable "autoscaling_capacity_providers" ](https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/45f532c06488d84f140af36241d164facb5e05f5/modules/cluster/variables.tf#L96C1-L96C43) gets passed down to [this block](https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/45f532c06488d84f140af36241d164facb5e05f5/modules/cluster/main.tf#L152) to propagate the managed_draining setting in the same way as is done for `managed_termination_protection`. This will need to be gated so that it is only set for aws provider 5.34.0 and above.

**Comment by easterbonbon** [comment]
Hey there, it sounds like the changes coming up in v6 may address your issue here. Here's the relevant PR: https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/158

**Comment by purplepangolin** [comment]
Thanks @easterbonbon, was just about to open a pr for that myself as I hadn't spotted that one.
