### ISSUE TITLE
Support Blue/Green Deployment CodeDeploy for ECS Service

### ISSUE THREAD

**Issue by monelgordillo** [terraform-aws-modules/terraform-aws-ecs#175]
## Is your request related to a new offering from AWS?
CodeDeploy is not a new offering. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_config
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_group
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_app

## Is your request related to a problem? Please describe.
We use blue/green deployments via CodeDeploy in the ECS service settings.
![image](https://github.com/terraform-aws-modules/terraform-aws-ecs/assets/36521543/8c073df6-cec4-45f2-bc02-dac127eb0f61)

## Describe the solution you'd like.
I would like to see CodeDeploy parameters available in the service submodule.

## Describe alternatives you've considered.
I'm going to search to see if maybe there's another 3rd party module that can do this.

**Comment by antonbabenko** [comment]
I think that AWS CodeDeploy doesn't belong to the main/root module, but we can consider adding support for the deployment as a separate independent submodule like it has been implemented in the Lambda module - https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/modules/deploy
