### ISSUE TITLE
Dynamic network configuration in service module fails for external deployments

### ISSUE THREAD

**Issue by oliverlambson** [terraform-aws-modules/terraform-aws-ecs#184]
## Description

In the service module, if `var.network_mode == "awsvpc"` and `local.is_external_deployment == true`, `terraform plan` cannot pass.

`local.is_external_deployment == true` if `var.deployment_controller = {type = "EXTERNAL"}`

Problem (./modules/service/main.tf#98):
```hcl
dynamic "network_configuration" {
    # Set by task set if deployment controller is external
    for_each = var.network_mode == "awsvpc" ? [{ for k, v in local.network_configuration : k => v if !local.is_external_deployment }] : [] # this line contains the bug

    content {
      assign_public_ip = network_configuration.value.assign_public_ip
      security_groups  = network_configuration.value.security_groups
      subnets          = network_configuration.value.subnets
    }
  }
```

Fix:
```hcl
dynamic "network_configuration" {
    # Set by task set if deployment controller is external
    for_each = var.network_mode == "awsvpc" && !local.is_external_deployment ? [local.network_configuration] : []

    content {
      assign_public_ip = network_configuration.value.assign_public_ip
      security_groups  = network_configuration.value.security_groups
      subnets          = network_configuration.value.subnets
    }
}
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: `v5.10.0`

- Terraform version: `Terraform v1.7.5 on darwin_amd64`
- Provider version(s): `provider registry.terraform.io/hashicorp/aws v5.43.0`

## Reproduction Code [Required]

Full example here: https://github.com/oliverlambson/terraform-aws-ecs/tree/bug/184/examples/bug-external-deployment

- Clone this repo
- cd into `./examples/fargate`
- run `terraform init`
- run `terraform plan` --> success
- add this code snippet on line 66 of `./examples/fargate/main.tf`
```hcl
  deployment_controller = {
    type = "EXTERNAL"
  }
```
- run `terraform plan` --> fail
```
│ Error: Unsupported attribute
│ 
│   on ../../modules/service/main.tf line 103, in resource "aws_ecs_service" "this":
│  103:       assign_public_ip = network_configuration.value.assign_public_ip
│     ├────────────────
│     │ network_configuration.value is object with no attributes
│ 
│ This object does not have an attribute named "assign_public_ip".
╵
╷
│ Error: Unsupported attribute
│ 
│   on ../../modules/service/main.tf line 104, in resource "aws_ecs_service" "this":
│  104:       security_groups  = network_configuration.value.security_groups
│     ├────────────────
│     │ network_configuration.value is object with no attributes
│ 
│ This object does not have an attribute named "security_groups".
╵
╷
│ Error: Unsupported attribute
│ 
│   on ../../modules/service/main.tf line 105, in resource "aws_ecs_service" "this":
│  105:       subnets          = network_configuration.value.subnets
│     ├────────────────
│     │ network_configuration.value is object with no attributes
│ 
│ This object does not have an attribute named "subnets".
```

## Expected behavior

- Plan should succeed
- the `for_each` in `./modules/service/main.tf:dynamic "network_configuration"` should evaluate to an empty list, but actually evaluates to a list containing an empty map: `[{}]`.

## Actual behavior

- Plain fails
- the `for_each` in `./modules/service/main.tf:dynamic "network_configuration"` evaluates to an empty list: `[]`

### Terminal Output Screenshot(s)

N/A

## Additional context

Minimal replication in `terraform console` shows that when `local.is_external_deployment == true && var.network_mode == "awsvpc"`, the `for_each` list becomes a list of length 1 containing an empty map, rather than an empty list
```
> "awsvpc" == "awsvpc" ? [{ for k, v in {assign_public_ip = "ENABLED", security_groups = ["sg-123456"], subnets = ["subnet-123456"]} : k => v if !true }] : []
tolist([
  {},
])
> "notawsvpc" == "awsvpc" ? [{ for k, v in {assign_public_ip = "ENABLED", security_groups = ["sg-123456"], subnets = ["subnet-123456"]} : k => v if !true }] : []
tolist([])
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.10.1 :tada:
