### ISSUE TITLE
Add TLS Support for ECS Service Connect with ACM PCA

### ISSUE THREAD

**Issue by steve-will-cf** [terraform-aws-modules/terraform-aws-ecs#193]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: [5.37.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5370-february-15-2024)

## Is your request related to a problem? Please describe.
Currently, the [terraform-aws-ecs](https://github.com/terraform-aws-modules/terraform-aws-ecs) module does not  support TLS for Service Connect.

## Describe the solution you'd like.
I would like to configure TLS for Service Connect to enable  traffic encryption.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-connect-tls.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#tls

## Additional context
This feature request was previously posted by someone else on Feb 16, 2024 but had gone stale.
https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/167
I hope that this post is appropriate as I'm unable to comment on the related issue as it has been closed.
Thanks for your consideration.

**Comment by douglas-woods** [comment]
I will add my vote to this request. 

I am using this module to create my services. Is there a workaround that I can use to configure service connect tls? (while still using this module)
