### ISSUE TITLE
Update aws provider version

### ISSUE THREAD

**Issue by mayank0202** [terraform-aws-modules/terraform-aws-ecs#194]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.

  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
Can we update aws provider version in `versions.tf`?

## Describe the solution you'd like.
 we can provide aws provider  version like this in the file
 ```
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0, < 6.0"
    }
  }
```
This will not impact the module and after updating we will test this module perfectly

**Comment by bryantbiggs** [comment]
what for? what problem are we trying to solve?

**Comment by mayank0202** [comment]
I am using this module in one of my repo and i was trying to update aws provider version which is `5.48 ` and its restricted to `4.66.1 `so thats why i suggested `version = ">= 4.0, < 6.0"` which wont impact any functionality .

**Comment by bryantbiggs** [comment]
no - we only regulate the minimum required version for the functionality offered. in some cases we will cap the upper bound version if there is a new major version thats breaking things, but its rare. 

so if you want to use features in `5.48` go for it - we don't stop you. if you are having trouble getting it to pull that, add the `-upgrade` to the init command, or check the other module requirements as one might be restricting the max version
