### ISSUE TITLE
Feature Request: Add Support for EBS Volumes

### ISSUE THREAD

**Issue by rosstimson-causaly** [terraform-aws-modules/terraform-aws-ecs#202]
## Is your request related to a new offering from AWS?

  - Yes ✅: [5.55.1](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5511-may-24-2024)

## Is your request related to a problem? Please describe.
I'd like to use Fargate containers that persist data on an EBS volume, for example, a SQLite database. I'm aware this wouldn't work well if scaling horizontally, that's not my use case though. 

## Describe the solution you'd like.
Allow the fairly new usage of EBS volumes with ECS.

## Describe alternatives you've considered.
Maybe an EBS volume can be created using standard provider resources and then attached to module created stuff but this doesn't seem right and it'd all break when a container got replaced I suspect.

## Additional context
Provider docs for the relevant resources are here:

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#volume_configuration
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#configure_at_launch

**Comment by bryantbiggs** [comment]
closed in #205
