### ISSUE TITLE
Why set `create_cloudwatch_log_group = false   enable_cloudwatch_logging   = false ` but it still create new log group?

### ISSUE THREAD

**Issue by dungle-rg** [terraform-aws-modules/terraform-aws-ecs#209]
Hi guys!
When I create my service with :
````
 create_cloudwatch_log_group = false
  enable_cloudwatch_logging   = false
  cloudwatch_log_group_name = aws_cloudwatch_log_group.this.name
```

I have seen that it still create new log group for service and i do not want as this.

**Comment by richardgavel-ordinaryexperts** [comment]
Are you sure the terraform module created it? Does a module.xxx.aws_cloudwatch_log_group.this resource appear in the state file? I assume your point is to have cloudwatch logging, but to a pre-existing log group? Do you also pass in your own logging_configuration?

**Comment by dungle-rg** [comment]
@richardgavel-ordinaryexperts I'm sure module created it!
