### ISSUE TITLE
cluster_tags also added to cloudwatch groups

### ISSUE THREAD

**Issue by jastsai** [terraform-aws-modules/terraform-aws-ecs#213]
## Description
from line:
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/048acceec64b26965ae29e14bd851725ec67d575/main.tf#L44
and eventually passed to
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/048acceec64b26965ae29e14bd851725ec67d575/modules/cluster/main.tf#L103

it looks like cluster_tags is also applied to the created cloudwatch group. Is it intentional or a bug?

here is the description from the readme
```
cluster_tags | A map of additional tags to add to the cluster
```

[cluster_tags](https://github.com/terraform-aws-modules/terraform-aws-ecs#input_cluster_tags)	A map of additional tags to add to the cluster
[cluster_tags](https://github.com/terraform-aws-modules/terraform-aws-ecs#input_cluster_tags)	A map of additional tags to add to the cluster

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 5.11.3

- Terraform version: 1.8.5

- Provider version(s): aws v5.59.0

## Expected behavior

the value defined in the variable cluster_tags only apply to ecs cluster

## Actual behavior

the value defined in the variable cluster_tags also applied to cloudwatch group

**Comment by bryantbiggs** [comment]
its not clear what you are pointing out - however, looking at the tags and their propagation, everything looks correct

**Comment by jastsai** [comment]
if I understand correctly, the cluster_tags should add additional tags to cluster only.
but the cluster_tags propagation is eventually merge and used in the ```resource "aws_cloudwatch_log_group" "this"```
