### ISSUE TITLE
Provider variable for service registry

### ISSUE THREAD

**Issue by sfiguereo** [terraform-aws-modules/terraform-aws-ecs#214]
## Is your request related to a new offering from AWS? sort of.
AWS has Route53Profiles that allow to share hosted zones and DNS resolutions between accounts.  I have been trying to set up a hub and spoke architecture where all member account register their services in a central account.  Current AWS Route53 allows for DNS resolution but the services need to be registered in the central account service_discovery_service.  The ECS module does not allow to change the provider in order to assume a role in the central account to register the ECS service in the service discovery service.  This limits the possibility of accomplishing this architecture as the registration in the central account currently will need to be done manually and require manual control of the target ips of the ECS containers.

## Is your request related to a problem? Please describe.

Let's break this down to clarify the key points:

Network Connectivity: Transit Gateway setup is correct and allows for cross-account DNS resolution. This is a good foundation for a centralized service discovery architecture.

DNS Resolution: The fact that you can resolve DNS from the member account to the central account's namespace is perfect. This means services in member accounts can potentially discover services registered in the central account.

Registration Limitation: The core issue is with registering the ECS service from the member account into the central account's service discovery service.

ECS Service Resource Limitation: the aws_ecs_service resource doesn't allow specifying a different provider for the service discovery registration part. This is a significant limitation in Terraform's AWS provider.

Given these constraints, here are some potential workarounds, though none are ideal:

Custom Registration Process:

Create the ECS service without service discovery.
Use a separate process (Lambda function, EC2 instance, or external script) to register the service in the central account's service discovery.
This process would need appropriate IAM permissions to assume a role in the central account.

Split Resource Creation:

Create the ECS service in Terraform without service discovery.
Create a separate aws_service_discovery_instance resource in Terraform, using a provider that assumes a role in the central account.
Manually link these together using the ECS service's IP or DNS name.

Centralized ECS Management:

Consider managing all ECS services from the central account, which would allow direct registration with the central service discovery.
Use cross-account IAM roles to allow the central account to manage ECS tasks in member accounts.

Alternative Service Mesh:
Implement a service mesh solution like AWS App Mesh, which has better support for cross-account scenarios.

## Describe the solution you'd like.
The ability to specify a different provider for the service_registries block in the aws_ecs_service resource would be a valuable addition.

## Describe alternatives you've considered.
the above options but none seems to be appropriate for my case.

## Additional context
I have conference with AWS consultants both in Route53 and Cloud Map who confirmed the need to register the services in the central account so that they can be discovered by other member accounts in a centralized architecture.

**Comment by bryantbiggs** [comment]
> The ability to specify a different provider for the service_registries block in the aws_ecs_service resource would be a valuable addition.

This is a flaw in the fundamental understanding of Terraform and how it works. You create the service registry resource on your own and provide that to this module

**Comment by sfiguereo** [comment]
The module does not find the already created registry resource when it is in a different account to the one the module is running n, preventing cross account service discovery registration.

Regards,

Santiago Figuereo, MD


On Aug 2, 2024, at 2:56 PM, Bryant Biggs ***@***.***> wrote:

﻿

The ability to specify a different provider for the service_registries block in the aws_ecs_service resource would be a valuable addition.

This is a flaw in the fundamental understanding of Terraform and how it works. You create the service registry resource on your own and provide that to this module

**Comment by bryantbiggs** [comment]
I would try forking the module and trying to achieve the outcome desired and we can take a look. But what you are describing does not sound feasible - and not from a module perspective, but from the perspective of Terraform and/or the AWS API
