### ISSUE TITLE
Add support for managed_storage_configuration block

### ISSUE THREAD

**Issue by Skaopap** [terraform-aws-modules/terraform-aws-ecs#215]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
  
Introduced with the provider version 5.59.0 : https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.59.0

## Is your request related to a problem? Please describe.

We want to use in our ECS project the fargate volume encryption with customer managed key, introduced in June by AWS : https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-ecs-aws-fargate-encrypt-ephemeral-storage-customer-managed-kms-keys/?nc1=h_ls

## Describe the solution you'd like.

Add an input to the module to configure the managed_storage_configuration block in the aws_ecs_cluster resource.

## Additional context

Terraform doc : https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster#managed_storage_configuration-block

Thank you for the awesome work 🫡

**Comment by bryantbiggs** [comment]
Resolved in #205
