### ISSUE TITLE
Module should chain-output "security_group_id" from child module "service"

### ISSUE THREAD

**Issue by partlythomas** [terraform-aws-modules/terraform-aws-ecs#220]
## Describe the solution you'd like.

The child module "service" is outputting the `security_group_id` tied to the ECS service. However, the "root" module does not further chain this output, making it inaccessible for module calls outside of this module.
This would be particularly useful in order to limit the network access scope between the load balancer and the ECS services, rather than just using the CIDR of the whole VPC.

**Comment by bryantbiggs** [comment]
it does, you just have to extract it from https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/3b70e1e46e1b96a2da7fbfe6e2c11d44009607f1/outputs.tf#L59-L62
