### ISSUE TITLE
setting variables task_exec_iam_role_arn and tasks_iam_role_arn is a no-op

### ISSUE THREAD

**Issue by hardboiled** [terraform-aws-modules/terraform-aws-ecs#228]
## Description

I am trying to understand what the [task_exec_iam_role_arn](https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/modules/service/variables.tf#L393-L397) and [tasks_iam_role_arn](https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/modules/service/variables.tf#L482C11-L486) variables are for. The description says `"Existing IAM role ARN"`, which I thought might mean I could pass an existing role ARN and this would be assigned to the task I'm creating. However, when I run terraform plan/apply when passing a value for these variables, terraform doesn't make any changes. Is this what they are supposed to be used for? If so, how can I assign an existing role to tasks.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Notes

I have cleared the .terraform directory and reinitialized the project

Versions are below:
```
$ terraform -version
Terraform v1.9.2
on darwin_arm64

$ terraform providers -version
Terraform v1.9.2
on darwin_arm64
+ provider [registry.terraform.io/hashicorp/aws](http://registry.terraform.io/hashicorp/aws) v5.60.0
+ provider [registry.terraform.io/hashicorp/random](http://registry.terraform.io/hashicorp/random) v3.6.2
```

## Reproduction Code [Required]

```
resource "aws_iam_role" "test_role" {
    name = "test_role"

    assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          Service = "ecs-tasks.amazonaws.com"
        }
      },
    ]
  })
}


module "my_service" {
  source  = "terraform-aws-modules/ecs/aws//modules/service"
  version = "5.9.3"

  name        = "my-service-${var.module_id}"
  task_exec_iam_role_arn = aws_iam_role.test_role.arn
  tasks_iam_role_arn = aws_iam_role.test_role.arn
 # ...
}
```

Not using workspaces and I have cleared the cache.

## Expected behavior

terraform plan/apply changes the resources when I add these variables.

## Actual behavior

Setting and/or changing these variables is ignored. Tasks aren't associated with the roles provided by these variables.

**Comment by psantus** [comment]
These are used only if create_iam_role and  create_task_exec_iam_role are respectively set to false. Otherwise the module creates the role and won't take your arn into consideration.
