### ISSUE TITLE
Add containerPortRange definition support for tasks

### ISSUE THREAD

**Issue by vdanyliv** [terraform-aws-modules/terraform-aws-ecs#234]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
  - 5.x.x

## Is your request related to a problem? Please describe.
Provide a task definition with the **containerPortRange** property.

## Describe the solution you'd like.
Update the outdated aws provider to version 5.x is the easiest solution.

## Describe alternatives you've considered.
⛔ 

## Additional context
Sometimes tasks require port range definition instead of a single one, the current version of the module doesn't support such a scenario.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.0 :tada:
