### ISSUE TITLE
How to connect to the ECS cluster over internet

### ISSUE THREAD

**Issue by saxenark** [terraform-aws-modules/terraform-aws-ecs#24]
Hi,

I have adapted the sample to run my cluster with nginx as a reverse proxy. However, I am not sure how to connect to the cluster / EC2 instance over internet. I have the private ips but I don't see a public ip except in the nat gateway. 

I am new to AWS/ECS/Terraform etc. Please advice.

Thanks

**Comment by antonbabenko** [comment]
Hi,

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance-connect.html

Please ask such general questions on StackOverflow or other designated forums.
