### ISSUE TITLE
Allow keeping CloudWatch log groups on destroy

### ISSUE THREAD

**Issue by mfulgo** [terraform-aws-modules/terraform-aws-ecs#247]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
It'd be convenient to have the option to keep logs when the module (or container definition) is destroyed. This would be useful in cases where one has a compliance or regulatory requirement to keep logs for a certain amount of time.

## Describe the solution you'd like.
Add an input variable - `cloudwatch_logs_skip_destroy`, similar to https://github.com/terraform-aws-modules/terraform-aws-lambda/commit/7256f7c226adf294bb6280f1fc4326d015e78d83

## Describe alternatives you've considered.
n/a

## Additional context
n/a

**Comment by bryantbiggs** [comment]
why?

**Comment by antonbabenko** [comment]
It also sounds like a valid use case for the ECS module.

**Comment by bryantbiggs** [comment]
I disagree - and if I look back through the Lambda PR that added support, that is the exact issue that I would wish to avoid by always ensuring the log groups are deleted if the resources that use them are also destroyed https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/563 

If compliance is the issue - you would typically ship these off to a logging account (and into S3 for cost savings) where users do not have access to delete/modify

**Comment by antonbabenko** [comment]
I agree, that we should always delete resources created by the module.

AFAIK, this flag was added in the Lambda module for cases where log groups may already exist, and we should use the existing log group. Lambda allows you to customize the log group names.

I may need to be corrected. Blame jetlag. :)

**Comment by bryantbiggs** [comment]
we do support using existing log groups, or log groups created outside of the module. But adding `cloudwatch_logs_skip_destroy` would intentionally leave log groups around after the resources are removed which will result in accruing charges and name conflict if you try to re-deploy the same resources again

and welcome back! boy am I glad this week is over, now time for some holiday R&R 😅

**Comment by mfulgo** [comment]
The lambda module supports existing log groups as well.

It's less of a convenience for ECS clusters, since one generally defines a lot fewer of those than Lambdas. I just noted that it was an option provided there and not here... 🤷

The added complexity probably isn't worth the trade-offs. Hopefully this issue will at least catch any other folks who come from that module looking for the flag.
