### ISSUE TITLE
Hello_world service fails - no capacity providers with a weight value greater than 0

### ISSUE THREAD

**Issue by jgilfoil** [terraform-aws-modules/terraform-aws-ecs#27]
Tried running the complete-ecs example, only changed the locals and tf backend settings, got this error:

`Error: InvalidParameterException: There are no capacity providers with a weight value greater than zero defined in the default capacity provider strategy. At least one capacity provider must have a weight value greater than zero specified. Update the cluster's default capacity provider strategy or specify a valid capacity provider strategy and try again. "hello_world"

root@b49da8a20338:/opt/test/terraform-aws-ecs/examples/complete-ecs# terraform --version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
`

**Comment by antonbabenko** [comment]
Fixed in #30, [v2.7.0](https://github.com/terraform-aws-modules/terraform-aws-ecs/releases/v2.7.0) has been just released.
