### ISSUE TITLE
Update deprecated resource

### ISSUE THREAD

**Issue by ekuongm** [terraform-aws-modules/terraform-aws-ecs#54]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
After upgrading the AWS Terraform provider to v4.0.0 a warning shows up with the following message:

`
│ Warning: Argument is deprecated 
│   with module.ecs_cluster.aws_ecs_cluster.this, 
│   on .terraform/modules/ecs_cluster/main.tf line 1, in resource "aws_ecs_cluster" "this":
│    1: resource "aws_ecs_cluster" "this" {
│ Use the aws_ecs_cluster_capacity_providers resource instead
│ (and one more similar warning elsewhere)
`

## Describe the solution you'd like.
Update the module to use the aws_ecs_cluster_capacity_providers resource

## Additional context
Deprecated resources are listed at the ECS Cluster Terraform documentation web
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster

**Comment by antonbabenko** [comment]
I can see this change was made here - https://github.com/hashicorp/terraform-provider-aws/pull/22783

Pull-request is welcome if anyone wants to do it.

**Comment by aric49** [comment]
Is anyone working on reviewing this PR?   I have some ECS clusters which inherit this module and I am experiencing this issue as well. Thanks in advance!

**Comment by Hellscythe94** [comment]
Bumping this since this is still open.
