### ISSUE TITLE
Add support for specifying configuration / log_configuration block

### ISSUE THREAD

**Issue by jfair9** [terraform-aws-modules/terraform-aws-ecs#56]
The aws_ecs_cluster resource provides the ability to specify a logging configuration to ship logs to cloud_watch or a s3_bucket. This feature was introduced back in 3.46.0. Is it possible to get this feature added to the module?

Example:

```
resource "aws_ecs_cluster" "test" {
  name = "example"

  configuration {
    execute_command_configuration {
      kms_key_id = aws_kms_key.example.arn
      logging    = "OVERRIDE"

      log_configuration {
        cloud_watch_encryption_enabled = true
        cloud_watch_log_group_name     = aws_cloudwatch_log_group.example.name
      }
    }
  }
}
```

**Comment by n1nj4-r4cc00n** [comment]
Hello over there I ran into this same scenario and it would be nice to have it up and running since is part of some security requirements I need to full fill. [Here](https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/57) is the PR to add the functionality.

**Comment by n1nj4-r4cc00n** [comment]
Hello any word on this? @antonbabenko
