### ISSUE TITLE
Complete example node cluster join fails

### ISSUE THREAD

**Issue by mbeacom** [terraform-aws-modules/terraform-aws-ecs#63]
## Description

Using `examples/complete/` as-is now results in the provisioned EC2 instances being unable to join the ECS cluster.
Toggling `enable_nat_gateway = true` on https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/c0ff594032845f4e82ea8ed1b15fdc4f182a84e0/examples/complete/main.tf#L178 resolves the inability to 

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `v4.0.1`
- Terraform version: `1.2.3` - `darwin_arm64`
- Provider version(s): `aws == v4.19.0`

## Reproduction Code [Required]

- `cd examples/complete/ && terraform init && terraform apply -auto-approve`

## Expected behavior

- Apply terraform
- Check ECS cluster instances (ec2 instance **does** join the cluster)
- Services become healthy (because the tasks are spun up and placed appropriately for the example).

## Actual behavior

- Apply terraform
- Check ECS cluster instances (ec2 instance **doesn't** join the cluster)
- Services don't become healthy (because the tasks can't be placed anywhere for the example).

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.2 :tada:
