### ISSUE TITLE
When I call module with create = false, then the terraform apply fails

### ISSUE THREAD

**Issue by sagarvelankar** [terraform-aws-modules/terraform-aws-ecs#65]
## Description

When I call module with create = false, then the terraform apply fails with below error

Error: Invalid index

on .terraform/modules/ecs/main.tf line 60, in locals:
60:     { for k, v in var.autoscaling_capacity_providers : k => merge(aws_ecs_capacity_provider.this[k], v) }
├────────────────
│ aws_ecs_capacity_provider.this is object with no attributes
│ 
│ The given key does not identify an element in this collection value.

## Versions

- Module version [Required]: 4.0.2 (latest)
- Terraform version: hashicorp/terraform:1.2.2
- Provider version(s): hashicorp/aws v4.19.0

## Reproduction Code [Required]

module "ecs" {

  source  = "terraform-aws-modules/ecs/aws"

  create = false

...
}

## Expected behavior

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

## Actual behavior

Error: Invalid index

on .terraform/modules/ecs/main.tf line 60, in locals:
60:     { for k, v in var.autoscaling_capacity_providers : k => merge(aws_ecs_capacity_provider.this[k], v) }
├────────────────
│ aws_ecs_capacity_provider.this is object with no attributes
│ 
│ The given key does not identify an element in this collection value.

## Additional context

If I change below line in the module main.tf line 60, in locals , then it succeeds

From

{ for k, v in var.autoscaling_capacity_providers : k => merge(aws_ecs_capacity_provider.this[k], v) }

To

{ for k, v in var.autoscaling_capacity_providers : k => merge(aws_ecs_capacity_provider.this[k], v) if var.create }

**Comment by bryantbiggs** [comment]
hmm, what does your configuration look like? We have these in our examples which work as intended without error https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/examples/complete/main.tf#L92
