### ISSUE TITLE
Add support for volumes in task definitions

### ISSUE THREAD

**Issue by compdemo0908** [terraform-aws-modules/terraform-aws-ecs#70]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
    - Yes ✅: please list the AWS provider version which introduced this functionality
 aws_ecs_task_definition add argument for volumes:
https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3450-june-10-2021
## Is your request related to a problem? Please describe.

Create services with task definitions that support volumes, i.e. EFS or FSx:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#volume

when finishing the TODO list for the service submodule:
https://github.com/terraform-aws-modules/terraform-aws-ecs/tree/master/modules/service
## Describe the solution you'd like.

Create a module input to support volume arguments in the aws_ecs_task_definition that's already in the TODO list of the Read.Me
## Describe alternatives you've considered.

This third party module:
https://github.com/techservicesillinois/terraform-aws-ecs-service#network_configuration
## Additional context

Third party module has too many co-dependencies and it's almost sunset. For example, when creating a service with a LB the Default Forward Rule can't be used but a Host Condition is required. Adding un-necessary complexity.

**Comment by antonbabenko** [comment]
Currently, this module is under active development, and such feature request is already among TODO's here - https://github.com/terraform-aws-modules/terraform-aws-ecs/tree/master/modules/service#todo

@bryantbiggs Please correct me if I am wrong.

**Comment by bryantbiggs** [comment]
correct - we will have support for this shortly

**Comment by gruckion** [comment]
This ticket shouldn't be closed as it's not yet resolved.

**Comment by vishwa-trulioo** [comment]
I noticed that there is a PR for this. When will this be rolled out?

**Comment by bryantbiggs** [comment]
soon - we are testing the changes against known patterns and examples first. It just takes some time but it is actively being worked on

**Comment by ahummel25** [comment]
> ref https://github.com/terraform-aws-modules/terraform-aws-ecs/compare/master...bryantbiggs:terraform-aws-ecs:feat/service?expand=1

When this PR is created and subsequently rolled out, will this allow creation of the actual ECS service and task definition? Or what all functionality will be included there?

**Comment by bryantbiggs** [comment]
Yes - this module should cover all of the different facets provided by ECS today (as supported by the Terraform provider of course)

**Comment by compdemo0908** [comment]
Thanks so much for actively working on this!

**Comment by victorcechinel** [comment]
Thanks so much for actively working on this!

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.0.0 :tada:
