### ISSUE TITLE
Getting issue with the cluster config. I am getting this error. Pls suggest. Thanks.

### ISSUE THREAD

**Issue by Anusha-Palanisamy** [terraform-aws-modules/terraform-aws-ecs#75]
terraform plan
╷
│ Error: Unsupported argument
│
│   on main.tf line 13, in module "ecs":
│   13:   cluster_name = local.name
│
│ An argument named "cluster_name" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on main.tf line 15, in module "ecs":
│   15:   cluster_configuration = {
│
│ An argument named "cluster_configuration" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on main.tf line 24, in module "ecs":
│   24:   autoscaling_capacity_providers = {
│
│ An argument named "autoscaling_capacity_providers" is not expected here.
╵

**Comment by bryantbiggs** [comment]
please fill in the issue template provided so we can properly triage and help troubleshoot
