### ISSUE TITLE
terraform registry files are empty

### ISSUE THREAD

**Issue by KamranBiglari** [terraform-aws-modules/terraform-aws-ecs#78]
## Description

Files in terraform cloud are empty. 
https://registry.terraform.io/modules/terraform-aws-modules/ecs/aws/5.0.0
please check the terraform cloud registry.

**Comment by bryantbiggs** [comment]
Could you elaborate?

**Comment by bryantbiggs** [comment]
Closing this for now since everything seems to be in order - feel free to respond here if there is more details on what is missing or empty
