### ISSUE TITLE
Error: Invalid for_each argument

### ISSUE THREAD

**Issue by berniedurfee-renaissance** [terraform-aws-modules/terraform-aws-ecs#82]
## Description

I can build everything from scratch, but when I try to change something, I get this error:

```
Error: Invalid for_each argument
on .terraform/modules/ecs/modules/service/main.tf line 525, in module "container_definition":
  for_each = { for k, v in var.container_definitions : k => v if local.create_task_definition }
local.create_task_definition is true
var.container_definitions will be known only after apply
The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.

When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.

Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
1.4.6 (Using Terraform Cloud)

- Provider version(s):
provider registry.terraform.io/hashicorp/aws v4.65.0

**Comment by bryantbiggs** [comment]
do you have some reproduction code that demonstrates this? Are you using a `depends_on` in your module definition?

**Comment by berniedurfee-renaissance** [comment]
It's internal code, I'd have to mock something up. I do depend on a couple other modules, so I added `depends_on = [module.efs, module.alb, module.alb_sg]` but I still get the same error.

If I teardown and rebuild from scratch, it works fine. If I make _some_ changes it works fine. But then sometimes is fails with that error and I have to rebuild from scratch to get it working again.

There's some discussions about this (https://github.com/hashicorp/terraform/issues/30838) and it seems like Terraform is working as intended. It seems like the module may need to declare a local variable, then use the result of that in the `for_each` to resolve the issue: https://github.com/hashicorp/terraform/issues/30838#issuecomment-1097920499

**Comment by bryantbiggs** [comment]
You should remove the explicit `depends_on` - Hashicorp advises against this for numerous reasons, one of which is the error you are reporting

**Comment by bryantbiggs** [comment]
closing out for now - please feel free to respond here with a reproduction and we can take another look
