### ISSUE TITLE
Separating service and task level placement constraints

### ISSUE THREAD

**Issue by david1437** [terraform-aws-modules/terraform-aws-ecs#85]
I am working on a project where I need to usee the placement constraint type "distinctInstance", however the placement_constraints variable applies to both the taskdefinition and service.  The issue is that distinctInstance can only be used in certain contexts https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html.  Specifically this section The distinctInstance constraint places each task in the group on a different instance. It can be specified with the following actions: [CreateService](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html), [UpdateService](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html), and [RunTask](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html).

## Describe the solution you'd like.
I see two possible solutions
1. Use two separate variables task_placement_constraints and service_placement_constraints
2. In aws_ecs_task_definition resource use a filter over foreach to remove distinctInstance types

## Describe alternatives you've considered.
Creating taskdefinition manually and then passing taskdefinition arn into the module, however this would take away a lot of features of the module and thus not preferred.

**Comment by david1437** [comment]
Yes so the distinctInstance type is only allowed at the service level so I want it to not set at the taskdefinition level.

error: expected placement_constraints.0.type to be one of [memberof], got distinctinstance module.ecs_service.aws_ecs_task_definition.this[0], │ on ecs_service\modules\service\main.tf line 608, in resource "aws_ecs_task_definition" "this": │ 608: resource "aws_ecs_task_definition" "this" {**

**Comment by bryantbiggs** [comment]
could you share the code you are using so I can reproduce on my end please?

**Comment by david1437** [comment]
module "ecs_cluster" {
  source  = "terraform-aws-modules/ecs/aws//modules/cluster"
  version = "5.0.1"

  cluster_name                          = var.id
  default_capacity_provider_use_fargate = false
  autoscaling_capacity_providers        = {
    ex-1 = {
      auto_scaling_group_arn         = module.autoscaling["ex-1"].autoscaling_group_arn
      managed_termination_protection = "ENABLED"
      managed_scaling                = {
        maximum_scaling_step_size = 1
        minimum_scaling_step_size = 1
        status                    = "ENABLED"
        target_capacity           = 60
      }
      default_capacity_provider_strategy = {
        weight = 100
        base   = 100
      }
    }
  }
}
module "ecs_service" {
  source  = "terraform-aws-modules/ecs/aws//modules/service"
  version = "5.0.1"

  name                           = "${var.id}-${var.environment}"
  cluster_arn                    = module.ecs_cluster.arn
  cpu                            = 1024 * 4
  memory                         = 4096 * 3
  ignore_task_definition_changes = true
  launch_type                    = "EC2"
  autoscaling_min_capacity       = 2
  autoscaling_max_capacity       = 2
  deployment_controller          = {
    type = "CODE_DEPLOY"
  }
  placement_constraints = {
    distinct = {
      type = "distinctInstance"
    }
  }
  requires_compatibilities   = ["EC2"]
  capacity_provider_strategy = {
    ex-1 = {
      capacity_provider = module.ecs_cluster.autoscaling_capacity_providers["ex-1"].name
      weight            = 1
      base              = 1
    }
  }
  container_definitions = {}
  load_balancer = {
    service = {
      target_group_arn = module.loadbalancer.target_group_arns[0]
      container_name   = "ws"
      container_port   = 5005
    }
  }
  subnet_ids           = module.network.private_subnets
  security_group_rules = {
    postgres_ingress = {
      type        = "ingress"
      from_port   = 5432
      to_port     = 5432
      protocol    = "tcp"
      description = "DB Port"
      cidr_blocks = module.network.private_subnets_cidr_blocks
    }
    redis_ingress = {
      type        = "ingress"
      from_port   = 6379
      to_port     = 6379
      protocol    = "tcp"
      description = "Cache Port"
      cidr_blocks = module.network.private_subnets_cidr_blocks
    }
    alb_ingress = {
      type        = "ingress"
      from_port   = 5005
      to_port     = 5005
      protocol    = "tcp"
      description = "Service Port"
      cidr_blocks = module.network.private_subnets_cidr_blocks
    }
    egress_all = {
      type        = "egress"
      from_port   = 0
      to_port     = 0
      protocol    = "-1"
      description = "Allow all outbound"
      cidr_blocks = ["0.0.0.0/0"]
    }
  }
  task_exec_iam_role_name     = "${var.id}-task-exec-role"
  task_exec_iam_role_policies = {

  }
  tasks_iam_role_name     = "${var.id}-task-role"
  tasks_iam_role_policies = {

  }
}

**Comment by david1437** [comment]
I have removed the container_definitions section as they have some company-specific stuff, let me know if you need any additional details

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.2.0 :tada:
