### ISSUE TITLE
port_mappings: InvalidParameterException, is used in more than one port mapping for container

### ISSUE THREAD

**Issue by chris-edwards-pub** [terraform-aws-modules/terraform-aws-ecs#89]
## Description

When defining a container definition under services I am defining the port_mappings to for port 53 tcp and udp. I am getting this error:

`InvalidParameterException: Container port 53 is used in more than one port mapping for container coredns-mysql`

I can create the same port tcp and udp in the aws gui without any issues and the json task file reflects the proper ports being opened.

```
  port_mappings = [
    {
      name          = local.container_name
      containerPort = 53
      hostPort      = 53
      protocol      = "tcp"
    },
    {
      name          = "${local.container_name}-53-udp"
      containerPort = 53
      hostPort      = 53
      protocol      = "udp"
    }
  ]
```

## Versions

- Module version [Required]:
5.0.1
- Terraform version: 
1.4.2

- Provider version(s):
hashicorp/aws v4.67.0

## Reproduction Code [Required]

```
  port_mappings = [
    {
      name          = local.container_name
      containerPort = 53
      hostPort      = 53
      protocol      = "tcp"
    },
    {
      name          = "${local.container_name}-53-udp"
      containerPort = 53
      hostPort      = 53
      protocol      = "udp"
    }
  ]
```

 NO
 YES
 Adding the same port to port_mappings except using the alternate protocol

## Expected behavior

I should be able to add port 53 tcp and  port 53 udp to port_mappings.

## Actual behavior

I get this error: `InvalidParameterException: Container port 53 is used in more than one port mapping for container coredns-mysql`

## Additional context

If you manually add the additional protocol through the aws gui it will not allow you to define a "Port name" and will have "Containername-Port-Protocol" greyed out in the "Port name"'s place.

**Comment by bryantbiggs** [comment]
this is not supported by ECS Fargate today unfortunately https://github.com/aws/containers-roadmap/issues/850

**Comment by chris-edwards-pub** [comment]
> this is not supported by ECS Fargate today unfortunately [aws/containers-roadmap#850](https://github.com/aws/containers-roadmap/issues/850)

Huh, should I just define my definition with a json file then?

**Comment by bryantbiggs** [comment]
I'm not sure I follow, how would the json file help? Its the AWS ECS API that is stating that once a port number is assigned, it can't be assigned again elsewhere - or at least that is my understanding

**Comment by chris-edwards-pub** [comment]
Gotcha!  Sorry, I didnt see that it was AWS I thought it was a Terraform issue.  Thanks.

**Comment by bryantbiggs** [comment]
@chris-edwards-pub I just learned some more details on this - would you mind sharing an example of your full configuration if you get a chance, please?
