### ISSUE TITLE
Allow the service to NOT have task CPU and Memory value being applied for EC2 launch types when Container CPU and Memory are set

### ISSUE THREAD

**Issue by asakapab0i** [terraform-aws-modules/terraform-aws-ecs#90]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Currently, the default values for Task Size CPU and Memory are 1024 and 2048 respectively, now this is different from the container CPU and Memory values.

What I want is an option to ignore the task definition  Task Size CPU and Memory because I already set up those values on the container level especially if the launch type is EC2. It is allowed in the UI but somehow on this module at the task level, the default values are being applied without even declaring it.

## Describe the solution you'd like.
So the solution would be that, if CPU and Memory are set at the container level and the launch type is EC2 then completely ignore Task level CPU and Memory unless it is explicitly declared.

**Comment by bryantbiggs** [comment]
the module is setup from a Fargate-first perspective. However, you can set the values under question to `null`
