### ISSUE TITLE
module not outputting task_exec_iam_role_name, task_exec_iam_role_arn

### ISSUE THREAD

**Issue by vagharsh** [terraform-aws-modules/terraform-aws-ecs#92]
in my terraform implementation of this module i have passed the values for this module 
```
      create_task_exec_iam_role = true
      create_task_exec_policy   = true
```

and i can confirm that the module is creating the resources both IAM role and Policy, but when i want to see the role name and arn in the outputs it sends blank ( null ) 

```
output "arn" {
  value = module.ecs.task_exec_iam_role_arn
}

output "name" {
  value = module.ecs.task_exec_iam_role_name
}
```

another approach i tried to pass policiy ARNs to the module using this  input `task_exec_iam_role_policies` 
but when passing it . i am getting this error. 

```
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/ecs/modules/service/main.tf line 781, in resource "aws_iam_role_policy_attachment" "task_exec_additional":
│  781:   for_each = { for k, v in var.task_exec_iam_role_policies : k => v if local.create_task_exec_iam_role }
│     ├────────────────
│     │ local.create_task_exec_iam_role is true
│     │ var.task_exec_iam_role_policies is a map of string, known only after apply
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this
│ resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
╵
```
this is how the input passing looks like
```
      task_exec_iam_role_policies = {
        "policy1" = aws_iam_policy.secret_manager_get_secret_policy.arn
        "policy1" = aws_iam_policy.allow_ssm_exec_policy.arn
      }
```
i also tried adding depends_on to the module so that my policies gets created first then the module but it's not affecting anything. 
any ideas on how to attach policies to my ECS successfully and why outputs not showing .?

using 
terraform : v1.4.2
module version :  5.0.0
AWS Provider : 5.0.1
OS : Mac OSX 13.4 (22F66)

thanks in advance

**Comment by bryantbiggs** [comment]
can you provide a reproduction so we can triage and provide guidance

**Comment by vagharsh** [comment]
what do you mean by reproduction ? 
how can i add policies externally to the role created by this module ?

**Comment by vagharsh** [comment]
i was able to add policies into the module finally but still curious on how not to inject policies into the module implementation . but add policies by using the module output task_exec_iam_role_arn  which is not working and returning null

**Comment by bryantbiggs** [comment]
This is an example of how policies are added in this module https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/b9be5742f32c63fd738cc32cc543cf673cac4a8f/examples/ec2-autoscaling/main.tf#L274-L277

For details on a reproduction https://github.com/bryantbiggs/how-to-create-reproduction

**Comment by vagharsh** [comment]
but why am i  getting the above mentioned error when doing that ?
with already created policies it's working , but in policies that the code will create is throwing the error

**Comment by bryantbiggs** [comment]
> but why am i getting the above mentioned error when doing that ?

Again, I don't know without seeing a full reproduction that I can reproduce on my end

**Comment by vagharsh** [comment]
```
module "ecs" {
  source = "terraform-aws-modules/ecs/aws"
  version = "5.0.0"

  cluster_name = "api-qa"

  tags = {
    Environment = "Test"
  }

  depends_on = [
    aws_iam_policy.secret_manager_get_secret_policy,
    aws_iam_policy.allow_ssm_exec_policy
  ]

  services = {
    wwno-rest-api-xylem-qa-vagharsh = {
      desired_count                      = 1
      launch_type                        = "FARGATE"
      platform_version                   = "LATEST"
      deployment_maximum_percent         = 200
      deployment_minimum_healthy_percent = 100
      assign_public_ip                   = false
      create_security_group              = true
      #      security_group_ids                 = ["sg-XXXXA"]
      subnet_ids                         = ["subnet-XXXX", "subnet-XXXY", "subnet-XXXZ"]
      health_check_grace_period_seconds  = 0
      scheduling_strategy                = "REPLICA"
      task_exec_iam_role_policies        = {
        "policy1": aws_iam_policy.secret_manager_get_secret_policy.arn
        "policy2": aws_iam_policy.allow_ssm_exec_policy.arn
      }

      create_task_exec_iam_role = true
      create_task_exec_policy   = true
      task_exec_iam_role_name   = "qa-TaskExecutionRole"

      ### task definition
      cpu                      = "2048"
      memory                   = "4096"
      network_mode             = "awsvpc"
      family                   = "api"
      requires_compatibilities = ["FARGATE"]
      container_definitions = {
        wwno-rest-api-vagharsh = {
          cpu       = 0
          essential = true
          image     = "12345.dkr.ecr.eu-central-1.amazonaws.com/api:0.1.0"
          port_mappings = [
            {
              containerPort = 8000,
              hostPort      = 8000,
              protocol      = "tcp"
            }
          ]
          log_configuration = {
            logDriver = "awslogs",
            options = {
              awslogs-group         = "api",
              awslogs-region        = "eu-central-1",
              awslogs-stream-prefix = "api"
            }
          }

          health_check = {
            command = [
              "CMD-SHELL",
              "curl -f http://127.0.0.1:8000/api/v1/health/ || exit 1"
            ],
            interval    = 35,
            timeout     = 30,
            retries     = 5,
            startPeriod = 300
          }
        }
      }
      ##
    }
  }
}

resource "aws_iam_policy" "allow_ssm_exec_policy" {
  name        = "qa-AllowSSMExec"
  path        = "/"
  description = "Allow SSm EXEC int"

  policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "ssmmessages:CreateControlChannel",
          "ssmmessages:CreateDataChannel",
          "ssmmessages:OpenControlChannel",
          "ssmmessages:OpenDataChannel"
        ],
        "Resource": "*"
      }
    ]
  })
}

resource "aws_iam_policy" "secret_manager_get_secret_policy" {
  name        = "qa-SecretManagerGetSecretPolicy"
  path        = "/"
  description = "Allow getting secret value"

  policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "secretsmanager:GetSecretValue"
        ],
        "Resource": [
          "arn:aws:secretsmanager:eu-central-1:123456:secret:eu-central-1/qa-XXXXX"
        ]
      }
    ]
  })
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.55.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}
```

**Comment by vagharsh** [comment]
module "ecs" {
  source = "terraform-aws-modules/ecs/aws"
  version = "5.0.0"

  cluster_name = "api-qa"

  tags = {
    Environment = "Test"
  }

  depends_on = [
    aws_iam_policy.secret_manager_get_secret_policy,
    aws_iam_policy.allow_ssm_exec_policy
  ]

  services = {
    qa = {
      desired_count                      = 1
      launch_type                        = "FARGATE"
      platform_version                   = "LATEST"
      deployment_maximum_percent         = 200
      deployment_minimum_healthy_percent = 100
      assign_public_ip                   = false
      create_security_group              = true
      #      security_group_ids                 = ["sg-XXXXA"]
      subnet_ids                         = ["subnet-XXXX", "subnet-XXXY", "subnet-XXXZ"]
      health_check_grace_period_seconds  = 0
      scheduling_strategy                = "REPLICA"
      task_exec_iam_role_policies        = {
        "policy1": aws_iam_policy.secret_manager_get_secret_policy.arn
        "policy2": aws_iam_policy.allow_ssm_exec_policy.arn
      }

      create_task_exec_iam_role = true
      create_task_exec_policy   = true
      task_exec_iam_role_name   = "qa-TaskExecutionRole"

      ### task definition
      cpu                      = "2048"
      memory                   = "4096"
      network_mode             = "awsvpc"
      family                   = "api"
      requires_compatibilities = ["FARGATE"]
      container_definitions = {
        api = {
          cpu       = 0
          essential = true
          image     = "12345.dkr.ecr.eu-central-1.amazonaws.com/api:0.1.0"
          port_mappings = [
            {
              containerPort = 8000,
              hostPort      = 8000,
              protocol      = "tcp"
            }
          ]
          log_configuration = {
            logDriver = "awslogs",
            options = {
              awslogs-group         = "api",
              awslogs-region        = "eu-central-1",
              awslogs-stream-prefix = "api"
            }
          }

          health_check = {
            command = [
              "CMD-SHELL",
              "curl -f http://127.0.0.1:8000/api/v1/health/ || exit 1"
            ],
            interval    = 35,
            timeout     = 30,
            retries     = 5,
            startPeriod = 300
          }
        }
      }
      ##
    }
  }
}

resource "aws_iam_policy" "allow_ssm_exec_policy" {
  name        = "qa-AllowSSMExec"
  path        = "/"
  description = "Allow SSm EXEC int"

  policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "ssmmessages:CreateControlChannel",
          "ssmmessages:CreateDataChannel",
          "ssmmessages:OpenControlChannel",
          "ssmmessages:OpenDataChannel"
        ],
        "Resource": "*"
      }
    ]
  })
}

resource "aws_iam_policy" "secret_manager_get_secret_policy" {
  name        = "qa-SecretManagerGetSecretPolicy"
  path        = "/"
  description = "Allow getting secret value"

  policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "secretsmanager:GetSecretValue"
        ],
        "Resource": [
          "arn:aws:secretsmanager:eu-central-1:123456:secret:eu-central-1/qa-XXXXX"
        ]
      }
    ]
  })
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.55.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

**Comment by vagharsh** [comment]
```
module "ecs" {
  source = "terraform-aws-modules/ecs/aws"
  version = "5.0.0"

  cluster_name = "api-qa"

  tags = {
    Environment = "Test"
  }

  depends_on = [
    aws_iam_policy.secret_manager_get_secret_policy,
    aws_iam_policy.allow_ssm_exec_policy
  ]

  services = {
    qa = {
      desired_count                      = 1
      launch_type                        = "FARGATE"
      platform_version                   = "LATEST"
      deployment_maximum_percent         = 200
      deployment_minimum_healthy_percent = 100
      assign_public_ip                   = false
      create_security_group              = true
      #      security_group_ids                 = ["sg-XXXXA"]
      subnet_ids                         = ["subnet-XXXX", "subnet-XXXY", "subnet-XXXZ"]
      health_check_grace_period_seconds  = 0
      scheduling_strategy                = "REPLICA"
      task_exec_iam_role_policies        = {
        "policy1": aws_iam_policy.secret_manager_get_secret_policy.arn
        "policy2": aws_iam_policy.allow_ssm_exec_policy.arn
      }

      create_task_exec_iam_role = true
      create_task_exec_policy   = true
      task_exec_iam_role_name   = "qa-TaskExecutionRole"

      ### task definition
      cpu                      = "2048"
      memory                   = "4096"
      network_mode             = "awsvpc"
      family                   = "api"
      requires_compatibilities = ["FARGATE"]
      container_definitions = {
        api = {
          cpu       = 0
          essential = true
          image     = "12345.dkr.ecr.eu-central-1.amazonaws.com/api:0.1.0"
          port_mappings = [
            {
              containerPort = 8000,
              hostPort      = 8000,
              protocol      = "tcp"
            }
          ]
          log_configuration = {
            logDriver = "awslogs",
            options = {
              awslogs-group         = "api",
              awslogs-region        = "eu-central-1",
              awslogs-stream-prefix = "api"
            }
          }

          health_check = {
            command = [
              "CMD-SHELL",
              "curl -f http://127.0.0.1:8000/api/v1/health/ || exit 1"
            ],
            interval    = 35,
            timeout     = 30,
            retries     = 5,
            startPeriod = 300
          }
        }
      }
      ##
    }
  }
}

resource "aws_iam_policy" "allow_ssm_exec_policy" {
  name        = "qa-AllowSSMExec"
  path        = "/"
  description = "Allow SSm EXEC int"

  policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "ssmmessages:CreateControlChannel",
          "ssmmessages:CreateDataChannel",
          "ssmmessages:OpenControlChannel",
          "ssmmessages:OpenDataChannel"
        ],
        "Resource": "*"
      }
    ]
  })
}

resource "aws_iam_policy" "secret_manager_get_secret_policy" {
  name        = "qa-SecretManagerGetSecretPolicy"
  path        = "/"
  description = "Allow getting secret value"

  policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "secretsmanager:GetSecretValue"
        ],
        "Resource": [
          "arn:aws:secretsmanager:eu-central-1:123456:secret:eu-central-1/qa-XXXXX"
        ]
      }
    ]
  })
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.55.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}
```

**Comment by vagharsh** [comment]
any update on this ? @bryantbiggs

**Comment by nick-bob** [comment]
@vagharsh i ran into this also. but i found that the role arn that i was looking for was in module.ecs.services.<service_name>.task_exec_iam_role_arn. i didn't look too deeply at what's going on but i my ecs cluster is only hosting workloads on fargate.

**Comment by bryantbiggs** [comment]
apologies but the code provided is still not deployable - we should be able to copy+paste and then `terraform init && terraform apply` the provided code to reproduce the issue. 

Instead, I would encourage you to refer to the examples we have provided https://github.com/terraform-aws-modules/terraform-aws-ecs/tree/master/examples

Closing this out for now, but if you have a deployable reproduction we can take another look
