### ISSUE TITLE
The task role arn is not getting updated.

### ISSUE THREAD

**Issue by aayushchhabra1999** [terraform-aws-modules/terraform-aws-ecs#98]
## Description
I am using this module to create ECS cluster, services, and containers. I also have a RDS database. The containers in the service need to connect to the database using IAM auth. I have create a "aws_iam_role" resource but I am not being able to attach this role to the containers. (Please look at code snippets below for more clarity).

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.5.0

- Provider version(s):
provider registry.terraform.io/hashicorp/aws v5.5.0

## Reproduction Code [Required]
![image](https://github.com/terraform-aws-modules/terraform-aws-ecs/assets/34938734/3e8dcfb1-b943-4cad-abd6-cce40de6f04c)

Line 34 in screenshot below is not taking effect.
![image](https://github.com/terraform-aws-modules/terraform-aws-ecs/assets/34938734/b5c63d54-bfc2-4553-be31-479a95b93664)

**Comment by bryantbiggs** [comment]
Thats not a valid variable name. The module creates a tasks IAM role for you so you can either add the permission with `tasks_iam_role_policies` or you can disable the role created by the module with `create_tasks_iam_role` and then pass your role via `tasks_iam_role_arn`
